const cartActionTypes = {
    TOGGLE_CART_VISIBILITY: "TOGGLE_CART_VISIBILITY",
    ADD_ITEM: "ADD_ITEM",
    REMOVE_ITEM: "REMOVE_ITEM",
    DECREASE_ITEM_QUANTITY: "DECREASE_ITEM_QUANTITY",
}

export default cartActionTypes;