const cartActionTypes = {
    TOGGLE_CART_VISIBILITY: "TOGGLE_CART_VISIBILITY",
    ADD_ITEM_START: "ADD_ITEM_START",
    ADD_ITEM_SUCCESS: "ADD_ITEM_SUCCESS",
    ADD_ITEM_FAILURE: "ADD_ITEM_FAILURE",
    REMOVE_ITEM_START: "REMOVE_ITEM_START",
    REMOVE_ITEM_SUCCESS: "REMOVE_ITEM_SUCCESS",
    REMOVE_ITEM_FAILURE: "REMOVE_ITEM_FAILURE",
    DECREASE_ITEM_QUANTITY_START: "DECREASE_ITEM_QUANTITY_START",
    DECREASE_ITEM_QUANTITY_SUCCESS: "DECREASE_ITEM_QUANTITY_SUCCESS",
    DECREASE_ITEM_QUANTITY_FAILURE: "DECREASE_ITEM_QUANTITY_FAILURE",
    CLEAR_CART: "CLEAR_CART",
    CLEAR_BACKEND_CART: "CLEAR_BACKEND_CART",
    GET_CURRENT_USER_CART: "GET_CURRENT_USER_CART"
}

export default cartActionTypes;